repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: detect-private-key
    - id: check-yaml
    - id: check-json
      files: \.(hcl|json)$
    - id: pretty-format-json
      args:
      - --autofix

-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.0
    hooks:
    - id: markdownlint
    - id: shellcheck
    - id: shfmt

-   repo: https://github.com/fortman/pre-commit-prometheus
    rev: v1.1.1
    hooks:
    - id: check-config
    - id: check-rules
